### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by Mohron** [kenijey/Levels#1]
levels-2.0

These loggers spam the console with information that's not particularly useful to a player or server and should be addressed.

https://github.com/kenijey/Levels/blob/d26bb0b99b3f61043d5f305dbbd8b94b90f5e162/src/main/java/com/kenijey/levels/event/EventLivingHurt.java#L238
https://github.com/kenijey/Levels/blob/d26bb0b99b3f61043d5f305dbbd8b94b90f5e162/src/main/java/com/kenijey/levels/event/EventLivingHurt.java#L245

**Comment by kenijey** [comment]
thank you.
