### ISSUE TITLE
Wierd game crash

### ISSUE THREAD

**Issue by Mongole** [kenijey/Levels#10]
https://paste.ee/p/EAP8a, https://paste.ee/p/HINJA, https://paste.ee/p/GmElK

So i get a crash which first happened when i was picking/dropping mob drops at night (whether at a fast or slow rate), then it happened when i was moving things into a cyclic bag of holding, and again it happened when i was hovering above items inside a backpacks! backpack and in the normal inventory, i though it was due to the TOP tooltip but it also happened when pointing on an empty inventory slot
Pointed at EventToolTip/ChangeToolTips.
The crash doesn't occure with the mod removed

Using forge 14.23.3.2702 and happens with weapons level 2.3.1 - 2.3.2

**Comment by Mongole** [comment]
Well i tested it for a few hours trying to duplicate the crash and seems like its all fixed, thanks!

**Comment by kenijey** [comment]
thank you too
