### ISSUE TITLE
Levels Gui doesn't show on key press

### ISSUE THREAD

**Issue by DatrixTHLK** [kenijey/Levels#2]
Hello,

I couldn't really press the default button since that was already taken. What I did was change the button from K to I because I wasn't taken. When I pressed "I" No gui screen comes up for it. My armor levels up as well as my weapons level up, but I can't do anything about it since no GUI shows up.

Minecraft 1.11.2
Forge: 13.20.1.2588
Levels 2: r1.2.8 ( I would have used Levels 3 3.0.2-beta, but seeing as that gives me a crash or outofbounds error out of boundary error or whatever it's called, I couldn't really use that) 

I will just have to forfeit the mod for now until a fix can be done, if one can be done. Note that since it has been nearly a year since an update for the mod has been done, I won't hold my breath for an update.

**Comment by kenijey** [comment]
oh no, it's not the right place for Levels 3 issues, this place is only for Levels 2 - Minecraft 1.12.2
