### ISSUE TITLE
Levels ignores previous copied items on player death

### ISSUE THREAD

**Issue by ichttt** [kenijey/Levels#5]
Hello,
it seems like you ignore already existing content in the new player [here](https://github.com/kenijey/Levels/blob/1e0b753fe1369ef753aca35ce5b778991c35445d/src/main/java/com/kenijey/levels/event/EventPlayerClone.java#L20)
This causes Tinker's Construct soulbound items to disappear, because TConstruct already removed them from the original player [here](https://github.com/SlimeKnights/TinkersConstruct/blob/d67cc3d00074608a4283df801602f21a6ff6da32/src/main/java/slimeknights/tconstruct/tools/modifiers/ModSoulbound.java#L51)

**Comment by kenijey** [comment]
will work on it. looks a bit confusing
