### ISSUE TITLE
When used with Sync, this causes inventory duplication

### ISSUE THREAD

**Issue by GreatestFool** [kenijey/Levels#7]
Though I do not know exactly what mechanic behind this is causing the problem. I do know that neither blacklisting Sync or disabling the two soulbound abilities. Though I suspect the soulbound mechanic in the mod is actually what is causing the issue.

**Comment by ichttt** [comment]
This is caused by the issues described in #5 and the comment next to it. Clearing the original inventory after copying the items will be sufficient.
